puts "The students of my cohort at Makers Academy"
puts "-------------------------------------------"
puts "Roi Driscoll"
puts "James Whyte"
puts "Margherita Serino"
puts "Vaidas Mykolaitis"
puts "Johann Bornman"
puts "Kate Hamilton"
puts "James Keap"
puts "Nic Yeeles"
puts "Julie Walker"
puts "Will Allen"
puts "Julia Tan"
puts "Federico Maffei"
puts "Jamie Patel"
puts "Faezrah Rizalman"
puts "Josh Fail-Brown"
puts "Sasha Cooper"
puts "Nicolai DTH"
puts "Nadav Matalon"
puts "Fitsum Teklehaimanot"
